title: "[HELP] Briefly describe your issue"
labels: ["help"]
body:
  - type: markdown
    attributes:
      value: |
        ## Need Help? 🛠️
        Please provide as much detail as possible so we can assist you effectively.

        **Tips:**
        - Be specific about the problem.
        - Include any error messages, screenshots, or logs.
        - If applicable, provide code snippets to help reproduce the issue.

  - type: textarea
    id: problem-description
    attributes:
      label: Problem description
      description: Clearly explain the issue you're facing.
      placeholder: "What are you trying to achieve? What is going wrong?"
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: List the steps to replicate the issue.
      placeholder: |
        1. Open the application
        2. Navigate to X
        3. See the error
    validations:
      required: false

  - type: input
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
      placeholder: "Expected outcome"
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Include any relevant information such as environment details (e.g., OS, browser, software versions).
      placeholder: "Operating system, browser, tool versions, etc."
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ### Thank you for providing the details!
        We'll get back to you as soon as possible.
